routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('usuarios', 'Usuario\UsuariosController');
        Route::resource('clientes', 'Cliente\ClientesController');
    });

    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('empresas', 'Empresa\EmpresasController');
        Route::resource('funcionarios', 'Funcionario\FuncionariosController');
        Route::resource('fornecedores', 'Fornecedor\FornecedoresController');
        Route::resource('medidas', 'Medida\MedidasController');
        Route::resource('rotulos', 'Rotulo\RotulosController');
        Route::resource('natureza-operacao', 'NaturezaOperacao\NaturezaOperacaoController');
        Route::resource('cargos', 'Cargo\CargosController');
    });



    Route::group(['prefix' => 'ajax'], function () {
        Route::get('cidades/{estadoId}', 'Cidade\CidadesController@getCidades');
    });







    Route::get('/', function () { return view('home.home'); })->name('home');

});


Auth::routes();

app/Http/Controllers/Cargo/CargosController.php
<?php

namespace SqlEstoque\Http\Controllers\Cargo;

use Illuminate\Http\Request;
use SqlEstoque\Http\Controllers\Controller;

// Repository
use SqlEstoque\Repositories\CargoRepository;

// Request
use SqlEstoque\Http\Requests\Cargo\StoreCargo;
use SqlEstoque\Http\Requests\Cargo\UpdateCargo;

class CargosController extends Controller
{
    /**
     * Repositorio
     * @var CargoRepository
     */
    private $repository;

    /**
     * Contrução da classe
     * @param EmpresaRepository $repository
     */
    public function __construct(CargoRepository $repository) {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $cargos = $this->repository->todosCargos($request);
        return view('cargos.index', compact('cargos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menuPermissoes = $this->repository->getPermissoes();
        return view('cargos.create', compact('menuPermissoes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCargo $request)
    {
        $data = $request->all();
        $this->repository->store($data);

        return \Redirect::route('cargos.index')
        ->with('success', [
            'title' => 'Cargo cadastrado',
            'message' => 'Cargo cadastrado com sucesso'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCargo $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/cargos/_form.blade.php
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#dados_principais" data-toggle="tab">Dados principais</a></li>
        <li><a href="#permissoes" data-toggle="tab">Permissões</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="dados_principais">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
                        <label for="exampleInputEmail1">Nome cargo</label>
                        <input type="text" class="form-control" value="{{ old('descricao',  isset($cargo->descricao) ? $cargo->descricao : null) }}" name="descricao" id="descricao" placeholder="Nome cargo">
                        @if ($errors->has('descricao'))
                        <span class="help-block">
                        <strong>{{ $errors->first('descricao') }}</strong>
                        </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="permissoes">
            @if ($errors->has('permissoes.0'))
                <div class="row">
                    <div class="col-md-12{{ $errors->has('permissoes.0') ? ' has-error' : '' }}">
                        <span class="help-block">
                        <strong>{{ $errors->first('permissoes.0') }}</strong>
                        </span>
                    </div>
                </div>
            @endif
            <div class="row">
                
                @foreach($menuPermissoes as $menu)
                    @if (count($menu['permissao']) > 0) 
                    <div class="col-md-3">
                        <table class="table table-bordered table-striped table-hover">
                            <tbody>
                                <tr>
                                    <th>{{$menu['descricao']}}</th>
                                    <th><input type="checkbox" class="checkbox-permission selecionar-tudo"></th>
                            
                                </tr>
                                @foreach($menu['permissao'] as $permissao)
                                <tr>
                                    <td>{{$permissao['label']}}</td>
                                    <td><input type="checkbox" class="checkbox-permission" name="permissoes[]" value="{{$permissao['id']}}"></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>
</div>
@if($errors->has('permissoes.0') == true AND $errors->has('descricao') == false)
    

@push('scripts')
<script type="text/javascript">
    $("a[href='#permissoes']").click();
</script>
@endpush


@endif

resources/views/cargos/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cargos
        <small>Cadastro de cargo</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Cadastrar cargo</h3>
        </div>
        <form role="form" method="POST" action="{{ route('cargos.store') }}" enctype="multipart/form-data" novalidate>
            {{ csrf_field() }}
            <div class="box-body">
                @include('cargos._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/cargos/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Empresas
        <small>Editar empresa</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Editar empresa</h3>
        </div>
        <form role="form" method="POST" action="{{ route('empresas.update', $empresa->id) }}" enctype="multipart/form-data" novalidate>
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
            <div class="box-body">
                @include('empresas._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/cargos/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cargos
        <small>Listagem de cargos</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    @include('includes.messages')

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Pesquisar</h3>
            <div class="box-tools">
                <a href="{{ route('cargos.create') }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-plus"></i> Adicionar cargo</a>
            </div>
        </div>
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <form method="GET">
                        <div class="input-group margin">
                            <input type="text" class="form-control" value="{{Request::input('search')}}" name="search" placeholder="Digite o conteudo que deseja buscar">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i> Pesquisa</button>
                                </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> Listagem</h3>
        </div>
        <div class="box-body">

            <table class="table table-bordered table-striped table-hover">
                <tbody>
                    <tr>
                        <th>#</th>
                        <th>Função</th>
                        <th>Ações</th>
                    </tr>
                   
                    @foreach($cargos as $cargo)
                    <tr>
                        <td>{{ $cargo->id }}</td>
                        <td>{{ $cargo->descricao }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('cargos.show', $cargo->id) }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-eye"></i></a>
                                <a href="{{ route('cargos.edit', $cargo->id) }}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a>
                                <button type="submit" class="btn btn-default btn-sm delete-data"><i class="fa fa-trash"></i></button>

                            </div>

                            <form class="url-form" role="form" method="POST" action="{{ route('cargos.destroy', $cargo->id) }}">
                                <input type="hidden" name="_method" value="delete">
                                {{ csrf_field() }}
                            </form>

                        </td>
                    </tr>
                    @endforeach
                   
                </tbody>
            </table>
        </div>
        {{--<div class="box-footer clearfix">
            <p class="no-margin pull-left">Foram encontrado {{$cargos->total()}} registro(s).</p>
            {{ $cargos->links('includes.pagination') }}
        </div>--}}
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/cargos/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Empresas
        <small>Visualizar empresa</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Visualizar empresa</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-3 text-center">
                    <dl>
                        <dt>LOGO</dt>
                        <dd><img src="data:image/png;base64, {{ $empresa->logotipo }}" alt="..." height="120" width="120" class="margin"></dd>
                    </dl>

                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>CNPJ</dt>
                        <dd>{{ $empresa->cnpj }}</dd>

                        <dt>Razão Social</dt>
                        <dd>{{ $empresa->razao_social }}</dd>

                        <dt>Nome fantasia</dt>
                        <dd>{{ $empresa->fantasia }}</dd>

                        <dt>Inscrição estadual</dt>
                        <dd>{{ $empresa->inscricao_estadual }}</dd>

                        <dt>Inscrição municipal</dt>
                        <dd>{{ $empresa->inscricao_municipal }}</dd>
                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Telefone</dt>
                        <dd>{{ $empresa->telefone }}</dd>

                        <dt>CEP</dt>
                        <dd>{{ $empresa->cep }}</dd>

                        <dt>Rua</dt>
                        <dd>{{ $empresa->rua }}</dd>

                        <dt>Número</dt>
                        <dd>{{ $empresa->numero }}</dd>

                        <dt>Complemento</dt>
                        <dd>{{ $empresa->complemento }}</dd>

                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Bairro</dt>
                        <dd>{{ $empresa->bairro }}</dd>

                        <dt>Cidade</dt>
                        <dd>{{ $empresa->cidade->nome }}</dd>

                        <dt>Estado</dt>
                        <dd>{{ $empresa->cidade->estado->nome }}</dd>

                        <dt>Email</dt>
                        <dd>{{ $empresa->email }}</dd>

                        <dt>Email contador</dt>
                        <dd>{{ $empresa->email_contador }}</dd>
                    </dl>
                </div>
            </div>
            <hr>
            <h4>Tributação</h4>
            <div class="row">
                <div class="col-md-3">
                    <dl>
                        <dt>Regime tributário</dt>
                        <dd>{{ $empresa->regime_tributario->descricao }}</dd>

                        <dt>Cnae principal</dt>
                        <dd>{{ $empresa->cnae_principal->descricao }}</dd>

                        <dt>Cnae secundário</dt>
                        <dd>{{ $empresa->cnae_secundario->descricao }}</dd>

                    </dl>
                </div>

                <div class="col-md-3">
                    <dl>
                        <dt>PIS</dt>
                        <dd>{{ $empresa->pis }}</dd>

                        <dt>CONFINS</dt>
                        <dd>{{ $empresa->confis }}</dd>


                    </dl>
                </div>

                <div class="col-md-3">
                    <dl>
                        <dt>IR</dt>
                        <dd>{{ $empresa->ir }}</dd>

                        <dt>CSLL</dt>
                        <dd>{{ $empresa->csll }}</dd>


                    </dl>
                </div>

                <div class="col-md-3">
                    <dl>
                        <dt>ISS</dt>
                        <dd>{{ $empresa->iss }}</dd>

                        <dt>INSS</dt>
                        <dd>{{ $empresa->inss }}</dd>
                    </dl>
                </div>
            </div>
            <hr>
            <h4>NFe</h4>
            <div class="row">
                <div class="col-md-3">
                    <dl>
                        <dt>Serie</dt>
                        <dd>{{ $empresa->serie }}</dd>

                        <dt>Núm. homologação</dt>
                        <dd>{{ $empresa->num_hom }}</dd>
                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Série recibo</dt>
                        <dd>{{ $empresa->serie_recibo }}</dd>

                        <dt>Número recibo</dt>
                        <dd>{{ $empresa->numero_recibo }}</dd>
                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Núm. Produção</dt>
                        <dd>{{ $empresa->num_prod }}</dd>
                        <dt>Status</dt>
                        <dd>{{ $empresa->status->descricao }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

</section>
<!-- /.content -->
@endsection