routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('usuarios', 'Usuario\UsuariosController');
        Route::resource('clientes', 'Cliente\ClientesController');
    });

    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('empresas', 'Empresa\EmpresasController');
        Route::resource('funcionarios', 'Funcionario\FuncionariosController');
        Route::resource('fornecedores', 'Fornecedor\FornecedoresController');
        Route::resource('medidas', 'Medida\MedidasController');
        Route::resource('rotulos', 'Rotulo\RotulosController');
        Route::resource('natureza-operacao', 'NaturezaOperacao\NaturezaOperacaoController');
        Route::resource('cargos', 'Cargo\CargosController');
    });



    Route::group(['prefix' => 'ajax'], function () {
        Route::get('cidades/{estadoId}', 'Cidade\CidadesController@getCidades');
    });







    Route::get('/', function () { return view('home.home'); })->name('home');

});


Auth::routes();

app/Http/Controllers/Cliente/ClientesController.php
<?php

namespace SqlEstoque\Http\Controllers\Cliente;

use Illuminate\Http\Request;
use SqlEstoque\Http\Controllers\Controller;

// Entities
use SqlEstoque\Entities\Status;
use SqlEstoque\Entities\Estado;
use SqlEstoque\Entities\User;
use SqlEstoque\Entities\Plano;

// Repository
use SqlEstoque\Repositories\ClienteRepository;

// Request
use SqlEstoque\Http\Requests\Cliente\StoreCliente;
use SqlEstoque\Http\Requests\Cliente\UpdateCliente;

class ClientesController extends Controller
{
    /**
     * Repositorio
     * @var ClienteRepository
     */
    private $repository;

    /**
     * Contrução da classe
     * @param ClienteRepository $repository
     */
    public function __construct(ClienteRepository $repository) {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clientes = $this->repository->todosClientes($request);
        $clientes->appends($request->toArray());

        return view('clientes.index', compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'estados' => Estado::orderBy('nome', 'asc')->get(),
            'planos' => Plano::orderBy('id')->get()
        ];

        return view('clientes.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCliente $request)
    {
        $data = $request->all();

        $this->repository->store($data);

        return \Redirect::route('clientes.index')
        ->with('success', [
            'title' => 'Cliente cadastrado',
            'message' => 'Cliente cadastrado com sucesso'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cliente = $this->repository->getById($id);

        return view('clientes.show', compact('cliente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'cliente' => $this->repository->getbyId($id),
            'planos' => Plano::orderBy('id')->get(),
            'estados' => Estado::orderBy('nome', 'asc')->get(),
            'status' => Status::whereIn('id', [
                Status::ATIVO,
                Status::BLOQUEADO,
                Status::PENDENTE
            ])->get()
        ];

        return view('clientes.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCliente $request, $id)
    {
        $data = $request->all();

        if (in_array((int)$data['status_id'], [2, 3]))
            User::where(['cliente_id' => $id, 'status_id' => 1])->update(['status_id' => 4]);
        else if((int)$data['status_id'] == 1)
            User::where(['cliente_id' => $id, 'status_id' => 4])->update(['status_id' => 1]);

        $this->repository->update($data, $id);

        return \Redirect::route('clientes.index')
        ->with('success', [
            'title' => 'Cliente editado',
            'message' => 'Cliente editado com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cliente = $this->repository->find($id);

        $cliente->status_id = 5;
        $cliente->users()->update(['status_id' => 4]);

        $cliente->save();

        return \Redirect::route('clientes.index')
        ->with('success', [
            'title' => 'Cliente excluído',
            'message' => 'Cliente excluído com sucesso'
        ]);
    }
}

resources/views/clientes/_form.blade.php
<h4>Dados principais</h4>
<div class="row">
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('cnpj') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">CNPJ</label>
            <input type="text" class="form-control cnpj-mask" value="{{ old('cnpj',  isset($cliente->cnpj) ? $cliente->cnpj : null) }}" name="cnpj" id="cnpj" placeholder="CNPJ">
            @if ($errors->has('cnpj'))
            <span class="help-block">
            <strong>{{ $errors->first('cnpj') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('razao_social') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Razão social</label>
            <input type="text" class="form-control" value="{{ old('razao_social',  isset($cliente->razao_social) ? $cliente->razao_social : null) }}" name="razao_social" id="razao_social" placeholder="Razão social">
            @if ($errors->has('razao_social'))
            <span class="help-block">
            <strong>{{ $errors->first('razao_social') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('fantasia') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Fantasia</label>
            <input type="text" class="form-control" value="{{ old('fantasia',  isset($cliente->fantasia) ? $cliente->fantasia : null) }}" name="fantasia" id="fantasia" placeholder="Fantasia">
            @if ($errors->has('fantasia'))
            <span class="help-block">
            <strong>{{ $errors->first('fantasia') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('inscricao_estadual') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Inscrição estadual</label>
            <input type="text" class="form-control" value="{{ old('inscricao_estadual',  isset($cliente->inscricao_estadual) ? $cliente->inscricao_estadual : null) }}" name="inscricao_estadual" id="inscricao_estadual" placeholder="Inscrição estadual">
            @if ($errors->has('inscricao_estadual'))
            <span class="help-block">
            <strong>{{ $errors->first('inscricao_estadual') }}</strong>
            </span>
            @endif
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('inscricao_municipal') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Inscrição municipal</label>
            <input type="text" class="form-control" value="{{ old('inscricao_municipal',  isset($cliente->inscricao_municipal) ? $cliente->inscricao_municipal : null) }}" name="inscricao_municipal" id="inscricao_municipal" placeholder="Inscrição municipal">
            @if ($errors->has('inscricao_municipal'))
            <span class="help-block">
            <strong>{{ $errors->first('inscricao_municipal') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('telefone') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Telefone</label>
            <input type="text" class="form-control telefone-mask" value="{{ old('telefone',  isset($cliente->telefone) ? $cliente->telefone : null) }}" name="telefone" id="telefone" placeholder="Telefone">
            @if ($errors->has('telefone'))
            <span class="help-block">
            <strong>{{ $errors->first('telefone') }}</strong>
            </span>
            @endif
        </div>
    </div>

    <div class="col-md-3">
        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" value="{{ old('email',  isset($cliente->email) ? $cliente->email : null) }}" name="email" id="email" placeholder="Email">
            @if ($errors->has('email'))
            <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
            </span>
            @endif
        </div>
    </div>

    <div class="col-md-3">
        <div class="form-group{{ $errors->has('email_cobranca') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Email cobrança</label>
            <input type="email" class="form-control" value="{{ old('email_cobranca',  isset($cliente->email_cobranca) ? $cliente->email_cobranca : null) }}" name="email_cobranca" id="email_cobranca" placeholder="Email cobrança">
            @if ($errors->has('email_cobranca'))
            <span class="help-block">
            <strong>{{ $errors->first('email_cobranca') }}</strong>
            </span>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('plano_id') ? ' has-error' : '' }}">
            <label>Plano</label>
            <select class="form-control" name="plano_id" id="plano_id">
                @foreach ($planos as $plano)
                <option value="{{$plano->id}}" @if(isset($cliente->plano_id) && $cliente->plano_id == $plano->id) selected="selected" @endif>{{$plano->descricao}} - R${{$plano->preco}}</option>
                @endforeach
            </select>
            @if ($errors->has('plano_id'))
            <span class="help-block">
            <strong>{{ $errors->first('plano_id') }}</strong>
            </span>
            @endif
        </div>
    </div>
    @if (isset($cliente))
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('status_id') ? ' has-error' : '' }}">
            <label>Status</label>
            <select class="form-control" name="status_id" id="status_id" >
                <option value="" selected="" disabled=""> Selecione...</option>
                @foreach ($status as $statu)
                <option value="{{$statu->id}}" @if (old('status_id',  isset($cliente->status_id) ? $cliente->status_id : null) == $statu->id) {{"selected"}} @endif>{{$statu->descricao}}</option>
                @endforeach
            </select>
            @if ($errors->has('status_id'))
            <span class="help-block">
            <strong>{{ $errors->first('status_id') }}</strong>
            </span>
            @endif
        </div>
    </div>
    @endif
</div>


<hr>
<h4>Endereço</h4>
<div class="row">
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('cep') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">CEP</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control cep-mask" value="{{ old('cep',  isset($cliente->cep) ? $cliente->cep : null) }}" name="cep" id="cep" placeholder="CEP">
            </div>
            @if ($errors->has('cep'))
            <span class="help-block">
            <strong>{{ $errors->first('cep') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group{{ $errors->has('rua') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Logradouro</label>
            <input type="text" class="form-control" readonly value="{{ old('rua',  isset($cliente->rua) ? $cliente->rua : null) }}" name="rua" id="rua" placeholder="Logradouro">
            @if ($errors->has('rua'))
            <span class="help-block">
            <strong>{{ $errors->first('rua') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('numero') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Número</label>
            <input type="text" class="form-control" value="{{ old('numero',  isset($cliente->numero) ? $cliente->numero : null) }}" name="numero" id="numero" placeholder="Número">
            @if ($errors->has('numero'))
            <span class="help-block">
            <strong>{{ $errors->first('numero') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('complemento') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Complemento</label>
            <input type="text" class="form-control" value="{{ old('complemento',  isset($cliente->complemento) ? $cliente->complemento : null) }}" name="complemento" id="complemento" placeholder="Complemento">
            @if ($errors->has('complemento'))
            <span class="help-block">
            <strong>{{ $errors->first('complemento') }}</strong>
            </span>
            @endif
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('bairro') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Bairro</label>
            <input type="text" class="form-control" readonly value="{{ old('bairro',  isset($cliente->bairro) ? $cliente->bairro : null) }}" name="bairro" id="bairro" placeholder="Bairro">
            @if ($errors->has('bairro'))
            <span class="help-block">
            <strong>{{ $errors->first('bairro') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label>Estado</label>
            <select class="form-control" readonly="true" name="estado" id="estado" >
                <option value="" selected="" disabled=""> Selecione...</option>
                @foreach ($estados as $estado)
                <option value="{{$estado->id}}"  @if (old('estado',  isset($cliente->cidade->estado) ? $cliente->cidade->estado->id : null) == $estado->id) {{"selected"}} @endif>{{$estado->nome}}</option>
                @endforeach
            </select>
            @if ($errors->has('estado'))
            <span class="help-block">
            <strong>{{ $errors->first('estado') }}</strong>
            </span>
            @endif
        </div>
    </div>

    <div class="col-md-3">
        <div class="form-group{{ $errors->has('cidade_id') ? ' has-error' : '' }}">
            <label>Cidade</label>
            <select class="form-control" readonly="true" name="cidade_id" id="cidade_id" >
                <option value="" @if (!isset($cliente->cidade)) selected="" @endif disabled=""> Selecione...</option>
                @if (isset($cliente->cidade))
                    <option value="{{$cliente->cidade->id}}" selected>{{$cliente->cidade->nome}}</option>
                @endif
            </select>
            @if ($errors->has('cidade_id'))
            <span class="help-block">
            <strong>{{ $errors->first('cidade_id') }}</strong>
            </span>
            @endif
        </div>
    </div>
</div>

resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Clientes
        <small>Cadastro de cliente</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Cadastrar cliente</h3>
        </div>
        <form role="form" method="POST" action="{{ route('clientes.store') }}" novalidate>
            {{ csrf_field() }}
            <div class="box-body">
                @include('clientes._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Clientes
        <small>Editar cliente</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Editar cliente</h3>
        </div>
        <form role="form" method="POST" action="{{ route('clientes.update', $cliente->id) }}" novalidate>
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
            <div class="box-body">
                @include('clientes._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Clientes
        <small>Listagem de clientes</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    @include('includes.messages')

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Pesquisar</h3>
            <div class="box-tools">
                <a href="{{ route('clientes.create') }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-plus"></i> Adicionar cliente</a>
            </div>
        </div>
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <form method="GET">
                        <div class="input-group margin">
                            <input type="text" class="form-control" value="{{Request::input('search')}}" name="search" placeholder="Digite o conteudo que deseja buscar">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i> Pesquisa</button>
                                </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> Listagem</h3>
        </div>
        <div class="box-body">

            <table class="table table-bordered table-striped table-hover">
                <tbody>
                    <tr>
                        <th>Razão Social / Nome</th>
                        <th>CNPJ / CPF</th>
                        <th>Telefone</th>
                        <th>Email cobrança</th>
                        <th>Status</th>
                        <th>Usuários</th>
                        <th>Ações</th>
                    </tr>

                    @foreach($clientes as $cliente)
                    <tr>
                        <td>{{ $cliente->razao_social }}</td>
                        <td>{{ $cliente->cnpj }}</td>
                        <td>{{ $cliente->telefone }}</td>
                        <td>{{ $cliente->email_cobranca }}</td>
                        <td>{{ $cliente->status->descricao }}</td>
                        <td>{{ $cliente->users()->count() }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('clientes.show', $cliente->id) }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-eye"></i></a>
                                <a href="{{ route('clientes.edit', $cliente->id) }}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a>
                                <button type="submit" class="btn btn-default btn-sm delete-data"><i class="fa fa-trash"></i></button>

                            </div>

                            <form class="url-form" role="form" method="POST" action="{{ route('clientes.destroy', $cliente->id) }}">
                                <input type="hidden" name="_method" value="delete">
                                {{ csrf_field() }}
                            </form>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="box-footer clearfix">
            <p class="no-margin pull-left">Foram encontrado {{$clientes->total()}} registro(s).</p>
            {{ $clientes->links('includes.pagination') }}
        </div>
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/clientes/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Clientes
        <small>Visualizar cliente</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Visualizar cliente</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-3">
                    <dl>
                        <dt>CNPJ</dt>
                        <dd>{{ $cliente->cnpj }}</dd>

                        <dt>Razão Social</dt>
                        <dd>{{ $cliente->razao_social }}</dd>

                        <dt>Fantasia</dt>
                        <dd>{{ $cliente->fantasia }}</dd>

                        <dt>Inscrição estadual</dt>
                        <dd>{{ $cliente->inscricao_estadual }}</dd>

                        <dt>Inscrição municipal</dt>
                        <dd>{{ $cliente->inscricao_municipal }}</dd>
                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Telefone</dt>
                        <dd>{{ $cliente->telefone }}</dd>

                        <dt>CEP</dt>
                        <dd>{{ $cliente->cep }}</dd>

                        <dt>Rua</dt>
                        <dd>{{ $cliente->rua }}</dd>

                        <dt>Número</dt>
                        <dd>{{ $cliente->numero }}</dd>

                        <dt>Complemento</dt>
                        <dd>{{ $cliente->complemento }}</dd>

                    </dl>
                </div>
                <div class="col-md-3">
                    <dl>
                        <dt>Bairro</dt>
                        <dd>{{ $cliente->bairro }}</dd>

                        <dt>Cidade</dt>
                        <dd>{{ $cliente->cidade->nome }}</dd>

                        <dt>Estado</dt>
                        <dd>{{ $cliente->cidade->estado->nome }}</dd>

                        <dt>Email</dt>
                        <dd>{{ $cliente->email }}</dd>

                        <dt>Status</dt>
                        <dd>{{ $cliente->status->descricao }}</dd>
                    </dl>
                </div>

                <div class="col-md-3">
                    <dl>
                        <dt>Criado em:</dt>
                        <dd>{{ $cliente->created_at->format('d/m/Y') }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

</section>
<!-- /.content -->
@endsection