routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('usuarios', 'Usuario\UsuariosController');
        Route::resource('clientes', 'Cliente\ClientesController');
    });

    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('empresas', 'Empresa\EmpresasController');
        Route::resource('funcionarios', 'Funcionario\FuncionariosController');
        Route::resource('fornecedores', 'Fornecedor\FornecedoresController');
        Route::resource('medidas', 'Medida\MedidasController');
        Route::resource('rotulos', 'Rotulo\RotulosController');
        Route::resource('natureza-operacao', 'NaturezaOperacao\NaturezaOperacaoController');
        Route::resource('cargos', 'Cargo\CargosController');
    });



    Route::group(['prefix' => 'ajax'], function () {
        Route::get('cidades/{estadoId}', 'Cidade\CidadesController@getCidades');
    });







    Route::get('/', function () { return view('home.home'); })->name('home');

});


Auth::routes();

app/Http/Controllers/Rotulo/RotulosController.php
<?php

namespace SqlEstoque\Http\Controllers\Rotulo;

use Illuminate\Http\Request;
use SqlEstoque\Http\Controllers\Controller;

// Repository
use SqlEstoque\Repositories\RotuloRepository;

// Requests
use SqlEstoque\Http\Requests\Rotulo\StoreRotulo;
use SqlEstoque\Http\Requests\Rotulo\UpdateRotulo;


class RotulosController extends Controller
{
    /**
     * Repositorio
     * @var RotuloRepository
     */
    private $repository;

    /**
     * Contrução da classe
     * @param RotuloRepository $repository
     */
    public function __construct(RotuloRepository $repository) {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $rotulos = $this->repository->todosRotulos($request['search']);
        return view('rotulos.index', compact('rotulos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('rotulos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRotulo $request)
    {
        $request = $request->all();

        $this->repository->store($request);

        return \Redirect::route('rotulos.index')
        ->with('success', [
            'title' => 'Rótulo cadastrado',
            'message' => 'Rótulo cadastrado com sucesso'
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rotulo = $this->repository->getById($id);
        return view('rotulos.edit', compact('rotulo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRotulo $request, $id)
    {
        $request = $request->all();
        $this->repository->update($request, $id);

        return \Redirect::route('rotulos.index')
        ->with('success', [
            'title' => 'Rótulo editado',
            'message' => 'Rótulo editado com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->destroy($id);

        return \Redirect::route('rotulos.index')
        ->with('success', [
            'title' => 'Rótulo excluído',
            'message' => 'Rótulo excluído com sucesso'
        ]);
    }
}

resources/views/rotulos/_form.blade.php
<div class="row">
    <div class="col-md-3">
        <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
            <label for="exampleInputEmail1">Descrição</label>
            <input type="text" class="form-control" maxlength="45" value="{{ old('descricao',  isset($rotulo->descricao) ? $rotulo->descricao : null) }}" name="descricao" id="descricao" placeholder="Descrição">
            @if ($errors->has('descricao'))
            <span class="help-block">
            <strong>{{ $errors->first('descricao') }}</strong>
            </span>
            @endif
        </div>
    </div>
</div>

resources/views/rotulos/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rótulos
        <small>Cadastro de rótulos</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Cadastrar rótulo</h3>
        </div>
        <form role="form" method="POST" action="{{ route('rotulos.store') }}" novalidate>
            {{ csrf_field() }}
            <div class="box-body">
                @include('rotulos._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>
            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/rotulos/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rótulos
        <small>Editar rótulo</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Editar rótulo</h3>
        </div>
        <form role="form" method="POST" action="{{ route('rotulos.update', $rotulo->id) }}" novalidate>
            {{ method_field('PUT') }}
            {{ csrf_field() }}
            <div class="box-body">
                @include('rotulos._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/rotulos/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rótulos
        <small>Listagem de rótulos</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    @include('includes.messages')

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Pesquisar</h3>
            <div class="box-tools">
                <a href="{{ route('rotulos.create') }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-plus"></i> Adicionar rótulo</a>
            </div>
        </div>
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <form method="GET">
                        <div class="input-group margin">
                            <input type="text" class="form-control" value="{{Request::input('search')}}" name="search" placeholder="Digite o conteudo que deseja buscar">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i> Pesquisa</button>
                                </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> Listagem</h3>
        </div>
        <div class="box-body">

            <table class="table table-bordered table-striped table-hover">
                <tbody>
                    <tr>
                        <th>Descrição</th>
                        <th>Ações</th>
                    </tr>

                    @foreach($rotulos as $rotulo)
                    <tr>
                        <td>{{ $rotulo->descricao }}</td>
                        <td width="25%">
                            <div class="btn-group">
                                <a href="{{ route('rotulos.edit', $rotulo->id) }}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a>
                                <button type="submit" class="btn btn-default btn-sm delete-data"><i class="fa fa-trash"></i></button>

                            </div>

                            <form class="url-form" role="form" method="POST" action="{{ route('rotulos.destroy', $rotulo->id) }}">
                                <input type="hidden" name="_method" value="delete">
                                {{ csrf_field() }}
                            </form>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="box-footer clearfix">
            <p class="no-margin pull-left">Foram encontrado {{$rotulos->count()}} registro(s).</p>
        </div>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection