routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('usuarios', 'Usuario\UsuariosController');
        Route::resource('clientes', 'Cliente\ClientesController');
    });

    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('empresas', 'Empresa\EmpresasController');
        Route::resource('funcionarios', 'Funcionario\FuncionariosController');
        Route::resource('fornecedores', 'Fornecedor\FornecedoresController');
        Route::resource('medidas', 'Medida\MedidasController');
        Route::resource('rotulos', 'Rotulo\RotulosController');
        Route::resource('natureza-operacao', 'NaturezaOperacao\NaturezaOperacaoController');
        Route::resource('cargos', 'Cargo\CargosController');
    });



    Route::group(['prefix' => 'ajax'], function () {
        Route::get('cidades/{estadoId}', 'Cidade\CidadesController@getCidades');
    });







    Route::get('/', function () { return view('home.home'); })->name('home');

});


Auth::routes();

app/Http/Controllers/Funcionario/FuncionariosController.php
<?php

namespace SqlEstoque\Http\Controllers\Funcionario;


use Illuminate\Http\Request;
use SqlEstoque\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

// Repository
use SqlEstoque\Repositories\UsuarioRepository;
use SqlEstoque\Repositories\EmpresaRepository;

// Requests
use SqlEstoque\Http\Requests\Funcionario\StoreFuncionario;
use SqlEstoque\Http\Requests\Funcionario\UpdateFuncionario;

use SqlEstoque\Entities\Status;

class FuncionariosController extends Controller
{
    /**
     * Repositorio
     * @var UsuarioRepository
     */
    private $repository;

    private $empresaRepository;

    /**
     * Contrução da classe
     * @param UsuarioRepository $repository
     */
    public function __construct(UsuarioRepository $repository, EmpresaRepository $empresaRepository) {
        $this->repository = $repository;
        $this->empresaRepository = $empresaRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = $this->repository->todosFuncionarios($request['search']);
        $users->appends($request->toArray());
        return view('funcionarios.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('funcionarios.create', [
            'planos' => DB::table('plano')->get(),
            'empresas' => $this->empresaRepository->todasEmpresasUser()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFuncionario $request)
    {
        $data = $request->all();
        $data['password'] =  \Hash::make($request['password']);
        $data['cliente_id'] = $this->repository->cliente_id();

        $this->repository->store($data);

        return \Redirect::route('funcionarios.index')
        ->with('success', [
            'title' => 'Funcionário cadastrado',
            'message' => 'Funcionário cadastrado com sucesso'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->repository->getById($id);
        return view('funcionarios.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->repository->getById($id);
        $planos = DB::table('plano')->get();
        $empresas = DB::table('empresa')->get();
        $status = DB::table('status')->whereIn('id', [
            Status::ATIVO,
            Status::BLOQUEADO,
            Status::PENDENTE
        ])->get();

        return view('funcionarios.edit', compact('user', 'planos', 'status', 'empresas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFuncionario $request, $id)
    {
        $request = $request->all();

        if (isset($request['password']))
            $request['password'] =  \Hash::make($request['password']);
        else
            unset($request['password']);

        $this->repository->update($request, $id);

        return \Redirect::route('funcionarios.index')
        ->with('success', [
            'title' => 'Funcionário editado',
            'message' => 'Funcionário editado com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $user = $this->repository->find($id);

        $user->status_id = 5;

        $user->save();

        return \Redirect::route('funcionarios.index')
        ->with('success', [
            'title' => 'Funcionário excluído',
            'message' => 'Funcionário excluído com sucesso'
        ]);
    }
}

resources/views/funcionarios/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Funcionários
        <small>Cadastro de Funcionários</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Cadastrar funcionário</h3>
        </div>
        <form role="form" method="POST" action="{{ route('funcionarios.store') }}" novalidate>
            {{ csrf_field() }}
            <div class="box-body">
                @include('usuarios._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
            <input type="hidden" name="usuario_tipo_id" value="3">
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/funcionarios/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Funcionários
        <small>Editar funcionário</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Editar funcionário</h3>
        </div>
        <form role="form" method="POST" action="{{ route('funcionarios.update', $user->id) }}" novalidate>
            {{ method_field('PUT') }}
            {{ csrf_field() }}
            <div class="box-body">
                @include('usuarios._form')
            </div>
            <div class="box-footer">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-default">Limpar</button>
                </div>

            </div>
            <input type="hidden" name="usuario_tipo_id" value="3">
        </form>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/funcionarios/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Funcionários
        <small>Listagem de Funcionários</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->

    @include('includes.messages')

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Pesquisar</h3>
            <div class="box-tools">
                <a href="{{ route('funcionarios.create') }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-plus"></i> Adicionar funcionário</a>
            </div>
        </div>
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <form method="GET">
                        <div class="input-group margin">
                            <input type="text" class="form-control" value="{{Request::input('search')}}" name="search" placeholder="Digite o conteudo que deseja buscar">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i> Pesquisa</button>
                                </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> Listagem</h3>
        </div>
        <div class="box-body">

            <table class="table table-bordered table-striped table-hover">
                <tbody>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>

                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->cpf }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->status->descricao }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('funcionarios.show', $user->id) }}" class="btn btn-default btn-sm"><i class="fa fa-fw fa-eye"></i></a>
                                <a href="{{ route('funcionarios.edit', $user->id) }}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a>
                                <button type="submit" class="btn btn-default btn-sm delete-data"><i class="fa fa-trash"></i></button>

                            </div>

                            <form class="url-form" role="form" method="POST" action="{{ route('funcionarios.destroy', $user->id) }}">
                                <input type="hidden" name="_method" value="delete">
                                {{ csrf_field() }}
                            </form>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="box-footer clearfix">
            <p class="no-margin pull-left">Foram encontrado {{$users->total()}} registro(s).</p>
            {{ $users->links('includes.pagination') }}
        </div>
        <!-- /.box-body -->
    </div>
</section>
<!-- /.content -->
@endsection

resources/views/funcionarios/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Funcionários
        <small>Visualizar funcionário</small>
    </h1>
</section>
<!-- Main content -->
<section class="content">

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-search"></i> Visualizar funcionário</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <dl>
                        <dt>Nome</dt>
                        <dd>{{ $user->name }}</dd>

                        <dt>Email</dt>
                        <dd>{{ $user->email }}</dd>

                        <dt>CPF</dt>
                        <dd>{{ $user->cpf }}</dd>

                        <dt>Empresa</dt>
                        <dd>{{ $user->cliente->cnpj }} - {{ $user->cliente->razao_social }}</dd>

                        <dt>Criado em</dt>
                        <dd>{{ $user->created_at->format('d/m/Y') }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

</section>
<!-- /.content -->
@endsection